redhat-ztp/ztp-cluster-deploy

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/create-cluster-day2/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

When we use http for virtualmedia, small ISO needs
to be copied there. But for samba this small ISO
needs to be copied to the smb share path.

Copy to http/smb depending on the context

---

ai-deploy-cluster-remoteworker/roles/deploy-cluster/tasks/main.yml

Force the hostname in all master nodes, so they take the
one needed without relying on external dhcp

Update host names on master nodes

---

ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

This is a fix for "Permission denied" error during copy assisted-service-client:
`cannot create regular file '/here/assisted-service-client-1.0.0.tar.gz': Permission denied`
:Z allows to successfully mount local directory to the pod:
```
podman run -v $PWD:/here --rm ocpmetal/assisted-service:latest ls /here
ls: cannot open directory '/here': Permission denied
podman run -v $PWD:/here:Z --rm ocpmetal/assisted-service:latest ls /here
ADMINS
CONTRIBUTING.md
```

Fix for task: Install assisted service client

---

ai-deploy-cluster-remoteworker/roles/create-cluster-day2/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/deploy-cluster-day2/tasks/main.yml

This allows to just add remote worker nodes on an
existing cluster, without needing to have the da1
cluster into AI.

Pass the cluster settings when deploying day2

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/create-cluster-day2/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/create-cluster/tasks/main.yml

Add a new cluster_version setting, that allows to specify
the version of the cluster to install. By default is set
to 4.7

Add the ability to specify openshift version

---

ai-deploy-cluster-remoteworker/README.md
ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/playbook.yml
ai-deploy-cluster-remoteworker/requirements.yml
ai-deploy-cluster-remoteworker/roles/create-cluster-day2/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/create-cluster/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/expose-endpoints/templates/haproxy.cfg.j2
ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/modify_iso_for_worker.yaml
ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

Currently the playbook had only been tested
running from localhost. But shold be possible to run
remotely, by specifying an ip on the provisioner inventory
entry.
Several changes have been needed in order to make it
run from any server.

Modify playbook to be run from any host

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/modify_iso_for_worker.yaml
ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

This is the last bit that was superfluous. We can just
use temporary path and name the small iso with the
cluster name, and get rid of that extra setting.

Get rid of small iso path

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml
ai-deploy-cluster-remoteworker/roles/add-remote-workers/templates/racadm.sh

hostname command may return wrong ip address on a server with several network interfaces. Switched for using value from config instead of hardcoded hostname command.

Get http url from config file

---

ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

In order to run the playbook, several dependencies
are needed, and we were not installing those. Add the
missing packages to avoid the manual install
Fixes-issue: #32

Install missing packages

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/enroll-hosts/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/enroll-hosts/templates/ai-vm.xml

It was currently hardcoded to /var/lib/libvirt/images,
but it can cause issues depending on the system.
Fixes-issue: #49

Add the ability to configure libvirt images path

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/modify_iso_for_worker.yaml

When rootfs_url is not set, we can take the
cluster version and use a default var. This will
make it easier, for people not using local mirrors,
to just get the right rootfs for their version,
without having to investigate the final url.
Fixes-Issue: #54

Add a default value for rootfs url

---

ai-deploy-cluster-remoteworker/README.md
ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/deploy-cluster-day2/tasks/main.yml

In order to avoid extra reboots, we can configure the nodes
to point to the right ignition file from the start, so they
get their machine config details from the moment zero. In
order to do that, we can add a setting called profile, and
we can configure the specific setting in assisted installer
to configure the right machine config pool for the node

Allow to define the role for each worker

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/create-cluster/tasks/main.yml

For our RAN deployments, we need that the used SDN
is OVN Kubernetes, not the default OpenShiftSDN one
AI offers the possibility of configuring that, by patching
the install-config.yaml endpoint, so we are adding
this feature.

Modify SDN to be OVN Kubernetes

---

ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/templates/02-master-workload-partitioning.yaml

The filename of the drop-in configuration we need to add to enable workload
partitioning has changed (https://github.com/openshift/enhancements/pull/726),
so we follow.

Match workload partitioning name changes in kubelet

---

ai-deploy-cluster-singlenode/inventory/hosts.sample
common-roles/create-cluster/tasks/main.yml
common-roles/create-cluster/templates/install-config.json.j2

This commit adds install-config patches in case we want to install the cluster from a disconnected registry

Add release mirror parameters

---

common-roles/install-assisted-installer/tasks/main.yml

The task is using rhcos_base_iso, that is defined
on tasks executed later, so it doesn't have the
reference. Changing the order to fix it.

Change order of onprem-vars

---

ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/templates/crio.conf

Schema for the workload partitioning has changed. The cpushares value must be an integer.
Signed-off-by: Ian Miller <imiller@redhat.com>

Update crio.conf template for Workload Partitioning

---

ai-deploy-cluster-singlenode/inventory/hosts.sample

For SNO, this version works (in the "classic" mode) but also includes the fix
so that UEFI boot works as well.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>

Set the assisted-service version to v1.0.18.3

---

common-roles/offline-mirror-olm/tasks/main.yml
common-roles/offline-mirror-olm/templates/offline-operator-mirror.sh.j2
install-ai-operator/inventory/hosts.sample

Update the scripts to use registry.redhat.io credentials embedded in the
pull secret instead of requiring explicit credentials in the inventory
file.
Signed-off-by: Ian Miller <imiller@redhat.com>

Remove need for Red Hat credentials in inventory.

---

common-roles/offline-mirror-olm/templates/offline-operator-mirror.sh.j2

This is no longer used, and is causing the mirroring
to fail, as latest version of this is 4.6

Fix ose reference

---

common-roles/install-assisted-installer/tasks/main.yml

The block was missing the KUBECONFIG
env var

Add missing environment declaration

---

create-cluster-sno/inventory/hosts.sample
create-cluster-sno/templates/infra_env.yaml.j2

Assisted Service allows ignition configuration
for the initial images. Add the ability to inject it.

Add missing ignition override
