ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/add-remote-worker/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/add-remote-worker/templates/racadm.sh
ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

this is done by introducing a new inventory parameter bmc_type
racadm.sh is automating defining a virtual media and power cyceling the server
by it self is using racadm cli from dell which uses redfish APIs

add iDrac (Dell BMC) support

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/add-remote-worker/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/enroll-hosts/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml

racadm merge was hasteful 
it need at least these fixes.

fix bmc distinction conditions

---

ai-deploy-cluster-remoteworker/roles/deploy-cluster/tasks/main.yml

otherwise playbook progress and hit and error when trying to interact with day2 cluster

add wait for cluster to be installed

---

ai-deploy-cluster-remoteworker/README.md
ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml

Signed-off-by: melserngawy <melserng@redhat.com>

Prevent redeploy pre existing workers unless specified

---

ai-deploy-cluster-remoteworker/roles/create-cluster/tasks/main.yml
ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/modify_iso_for_worker.yaml

This line was removed in the past, but due to
problems with rebases it has been added again,
so remove it

Remove extra ai_iso_path

---

README.md

Add link to the wiki page

---

acm-spoke/enroll-clusters.yaml
acm-spoke/import_cluster.sh
acm-spoke/inventory/hosts.sample
acm-spoke/playbook.yml

Signed-off-by: melserngawy <melserng@redhat.com>

Fix item.name in enroll-cluster tasks and import-cluster script

---

acm-spoke/enroll-clusters.yaml

Signed-off-by: melserngawy <melserng@redhat.com>

Fix enroll cluster namespace

---

ai-deploy-cluster-singlenode/inventory/hosts.sample
ai-deploy-cluster-singlenode/roles/prepare-environment/tasks/main.yml

This is prone to changes, so better we add it to
the inventory, so it can be easily changed

Parameterize the base image for SNO

---

ai-deploy-cluster-remoteworker/roles/modify-iso-day2/tasks/modify_iso_for_worker.yaml

There was a typo in the check for rootfs_url conditional

Add fix for passing rootfs_url

---

ai-deploy-cluster-singlenode/README.md
ai-deploy-cluster-singlenode/roles/prepare-environment/tasks/main.yml

Hey, I added the httpd setup to SNO deploy. Had some time to update the readme while it was installing :)
@serngawy @yrobla

Fix httpd and update README (SNO)

---

ai-deploy-cluster-singlenode/inventory/hosts.sample
ai-deploy-cluster-singlenode/roles/prepare-environment/tasks/main.yml
common-roles/install-assisted-installer/tasks/main.yml

Hey, I added AI version selector and de-duplicated some of the vars.
Also tried to separate Dell settings from Supermicro settings in the hosts.sample.
It is passing prepare-environment phase as expected

Allow AI versions, deduplicate vars

---

acm-spoke/README.md
acm-spoke/enroll-clusters.yaml
acm-spoke/import_cluster.sh
acm-spoke/inventory/hosts.sample

Signed-off-by: melserngawy <melserng@redhat.com>

Add hw type to the cluster variables

---

ai-deploy-cluster-singlenode/inventory/hosts.sample
ai-deploy-cluster-singlenode/roles/create-cluster/tasks/main.yml
ai-deploy-cluster-singlenode/roles/deploy-cluster/tasks/main.yml
ai-deploy-cluster-singlenode/roles/prepare-environment/tasks/main.yml
common-roles/download-iso/tasks/main.yml
common-roles/install-assisted-installer/tasks/main.yml
common-roles/install-httpd/tasks/main.yml

Use the common roles to execute regular
tasks, to avoid duplicates

Reconcile latest changes with SNO

---

ai-deploy-cluster-remoteworker/inventory/hosts.sample
ai-deploy-cluster-remoteworker/playbook.yml
ai-deploy-cluster-singlenode/inventory/hosts.sample
ai-deploy-cluster-singlenode/playbook.yml
ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/defaults/main.yml
ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/tasks/main.yml
ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/templates/02-master-workload-partitioning.yaml
ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/templates/crio.conf
ai-deploy-cluster-singlenode/roles/enable-workload-partitioning/templates/kubelet.conf
common-roles/apply-custom-manifests/tasks/main.yml
common-roles/common/defaults/main.yml
common-roles/common/tasks/main.yml

This creates a manifest which configures the CRI-O and Kubelet workload
partitioning configuration as outlined in
https://github.com/openshift/enhancements/pull/703

Add enable-workload-partition to SNO deploy

---

acm-spoke/enroll-clusters.yaml

Fix for issue https://github.com/redhat-ztp/ztp-cluster-deploy/issues/89

Fix missing hw in the host-item

---

acm-spoke/enroll-clusters.yaml

The cluster secret take times to be created. adding retry to re-get the secret. 
https://github.com/redhat-ztp/ztp-cluster-deploy/issues/93

Fix missing cluster-secret

---

acm-spoke/enroll-clusters.yaml

by the stage. Register the result to trigger the retry logic.

Set pipefail to ensure errors in pulling the CRD and import get caught

---

ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml
ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/main.yml

Delete the host from list if it is a redeploy,
and also consider as valid the added-to-cluster hosts
Fixes-bug: #100

Fix the redeploy workflow

---

create-cluster-sno/README.md
create-cluster-sno/files/nmstate.yaml
create-cluster-sno/inventory/hosts.sample
create-cluster-sno/playbook.yml
create-cluster-sno/templates/agent_cluster_install.yaml.j2
create-cluster-sno/templates/baremetal_host.yaml.j2
create-cluster-sno/templates/cluster_deployment.yaml.j2
create-cluster-sno/templates/infra_env.yaml.j2

It configures and applies the needed manifests
for deploying an SNO cluster using AI operator
framework.

Add sample playbook for creating SNO

---

common-roles/install-assisted-installer/tasks/main.yml
common-roles/install-assisted-installer/templates/add-hive-config.yaml.j2

In order to enable hive we need to create
the right config crd

Enable hive configuration

---

create-cluster-sno/files/nmstate_ipv6.yaml
create-cluster-sno/inventory/hosts.sample

Add nmstate sample for ipv6 fixed ip

---

create-cluster-sno/templates/infra_env.yaml.j2

Fix typo on cluster name label

---

create-cluster-sno/inventory/hosts.sample
create-cluster-sno/playbook.yml
create-cluster-sno/roles/deploy_cluster/tasks/main.yml
create-cluster-sno/templates/infra_env.yaml.j2

Add correction for ntp, and additional fixes

---

install-ai-operator/README.md

Add instructions for deploying with dhcp6

---

create-cluster-sno/extra_manifests/02-master-workload-partitioning.yaml
create-cluster-sno/extra_manifests/03-chrony-ntp.yaml
create-cluster-sno/files/nmstate_interfaces.yaml
create-cluster-sno/files/nmstate_ipv6.yaml
create-cluster-sno/inventory/hosts.sample
create-cluster-sno/playbook.yml
create-cluster-sno/roles/deploy_cluster_with_policy/tasks/main.yml
create-cluster-sno/roles/deploy_cluster_with_policy/templates/site_config.yaml.j2
create-cluster-sno/roles/install-requirements/tasks/main.yml

Add fixes for create sno with policy generator

---

common-roles/offline-mirror-olm/templates/offline-operator-mirror.sh.j2

Mirror gitops operator

---

create-cluster-sno/roles/deploy_cluster_with_policy/templates/secret.yaml.j2

Add missing secret template for SNO
